Item/29918
fiskaltrust/portal-manual-doc pull request #16
Opened 2020-07-01 12:01 UTC by Boulard-Fontaine

Corrected content in respect of exports / fiscal archives

2020-07-02 10:11 UTC, magdignomad submitted a review, later dismissed

2020-07-02 22:23 UTC, AxelKutschera requested changes
Waiting for the update of the existing merge conflicts discussed with magdignomad.

2020-07-03 09:34 UTC, magdignomad approved these changes

2020-07-03 09:40 UTC, magdignomad submitted a review, later dismissed

2020-07-03 09:46 UTC, AxelKutschera submitted a review, later dismissed

2020-07-03 11:01 UTC, magdignomad submitted a review, later dismissed

2020-07-08 23:45 UTC, merged